@startuml

title __FORMATTER's Class Diagram__\n

  namespace com.github.mikephil.charting.formatter {
    interface com.github.mikephil.charting.formatter.ColorFormatter {
        {abstract} + getColor()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.DefaultAxisValueFormatter {
        # digits : int
        # mFormat : DecimalFormat
        + DefaultAxisValueFormatter()
        + getDecimalDigits()
        + getFormattedValue()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.DefaultFillFormatter {
        + getFillLinePosition()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.DefaultValueFormatter {
        # mDecimalDigits : int
        # mFormat : DecimalFormat
        + DefaultValueFormatter()
        + getDecimalDigits()
        + getFormattedValue()
        + setup()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    interface com.github.mikephil.charting.formatter.IAxisValueFormatter {
        {abstract} + getFormattedValue()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    interface com.github.mikephil.charting.formatter.IFillFormatter {
        {abstract} + getFillLinePosition()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    interface com.github.mikephil.charting.formatter.IValueFormatter {
        {abstract} + getFormattedValue()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.IndexAxisValueFormatter {
        - mValueCount : int
        - mValues : String[]
        + IndexAxisValueFormatter()
        + IndexAxisValueFormatter()
        + IndexAxisValueFormatter()
        + getFormattedValue()
        + getValues()
        + setValues()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.LargeValueFormatter {
        - mFormat : DecimalFormat
        - mMaxLength : int
        - mSuffix : String[]
        - mText : String
        + LargeValueFormatter()
        + LargeValueFormatter()
        + getDecimalDigits()
        + getFormattedValue()
        + getFormattedValue()
        + setAppendix()
        + setMaxLength()
        + setSuffix()
        - makePretty()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.PercentFormatter {
        # mFormat : DecimalFormat
        + PercentFormatter()
        + PercentFormatter()
        + getDecimalDigits()
        + getFormattedValue()
        + getFormattedValue()
    }
  }
  

  namespace com.github.mikephil.charting.formatter {
    class com.github.mikephil.charting.formatter.StackedValueFormatter {
        - mAppendix : String
        - mDrawWholeStack : boolean
        - mFormat : DecimalFormat
        + StackedValueFormatter()
        + getFormattedValue()
    }
  }
  

  com.github.mikephil.charting.formatter.DefaultAxisValueFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter
  com.github.mikephil.charting.formatter.DefaultFillFormatter .up.|> com.github.mikephil.charting.formatter.IFillFormatter
  com.github.mikephil.charting.formatter.DefaultValueFormatter .up.|> com.github.mikephil.charting.formatter.IValueFormatter
  com.github.mikephil.charting.formatter.IndexAxisValueFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter
  com.github.mikephil.charting.formatter.LargeValueFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter
  com.github.mikephil.charting.formatter.LargeValueFormatter .up.|> com.github.mikephil.charting.formatter.IValueFormatter
  com.github.mikephil.charting.formatter.PercentFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter
  com.github.mikephil.charting.formatter.PercentFormatter .up.|> com.github.mikephil.charting.formatter.IValueFormatter
  com.github.mikephil.charting.formatter.StackedValueFormatter .up.|> com.github.mikephil.charting.formatter.IValueFormatter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
