@startuml

title __JOBS's Class Diagram__\n

  namespace com.github.mikephil.charting.jobs {
    class com.github.mikephil.charting.jobs.AnimatedMoveViewJob {
        {static} - pool : ObjectPool<AnimatedMoveViewJob>
        + AnimatedMoveViewJob()
        {static} + getInstance()
        + onAnimationUpdate()
        {static} + recycleInstance()
        + recycleSelf()
        # instantiate()
    }
  }
  

  namespace com.github.mikephil.charting.jobs {
    abstract class com.github.mikephil.charting.jobs.AnimatedViewPortJob {
        # animator : ObjectAnimator
        # phase : float
        # xOrigin : float
        # yOrigin : float
        + AnimatedViewPortJob()
        + getPhase()
        + getXOrigin()
        + getYOrigin()
        + onAnimationCancel()
        + onAnimationEnd()
        + onAnimationRepeat()
        + onAnimationStart()
        + onAnimationUpdate()
        {abstract} + recycleSelf()
        + run()
        + setPhase()
        # resetAnimator()
    }
  }
  

  namespace com.github.mikephil.charting.jobs {
    class com.github.mikephil.charting.jobs.AnimatedZoomJob {
        # mOnAnimationUpdateMatrixBuffer : Matrix
        # xAxisRange : float
        # zoomCenterX : float
        # zoomCenterY : float
        # zoomOriginX : float
        # zoomOriginY : float
        {static} - pool : ObjectPool<AnimatedZoomJob>
        + AnimatedZoomJob()
        {static} + getInstance()
        + onAnimationCancel()
        + onAnimationEnd()
        + onAnimationRepeat()
        + onAnimationStart()
        + onAnimationUpdate()
        + recycleSelf()
        # instantiate()
    }
  }
  

  namespace com.github.mikephil.charting.jobs {
    class com.github.mikephil.charting.jobs.MoveViewJob {
        {static} - pool : ObjectPool<MoveViewJob>
        + MoveViewJob()
        {static} + getInstance()
        {static} + recycleInstance()
        + removePool()
        + run()
        # instantiate()
    }
  }
  

  namespace com.github.mikephil.charting.jobs {
    abstract class com.github.mikephil.charting.jobs.ViewPortJob {
        # pts : float[]
        # view : View
        # xValue : float
        # yValue : float
        + ViewPortJob()
        + getXValue()
        + getYValue()
    }
  }
  

  namespace com.github.mikephil.charting.jobs {
    class com.github.mikephil.charting.jobs.ZoomJob {
        # mRunMatrixBuffer : Matrix
        # scaleX : float
        # scaleY : float
        {static} - pool : ObjectPool<ZoomJob>
        + ZoomJob()
        {static} + getInstance()
        {static} + recycleInstance()
        + run()
        # instantiate()
    }
  }
  

  com.github.mikephil.charting.jobs.AnimatedMoveViewJob -up-|> com.github.mikephil.charting.jobs.AnimatedViewPortJob
  com.github.mikephil.charting.jobs.AnimatedViewPortJob .up.|> android.animation.Animator.AnimatorListener
  com.github.mikephil.charting.jobs.AnimatedViewPortJob .up.|> android.animation.ValueAnimator.AnimatorUpdateListener
  com.github.mikephil.charting.jobs.AnimatedViewPortJob -up-|> com.github.mikephil.charting.jobs.ViewPortJob
  com.github.mikephil.charting.jobs.AnimatedZoomJob .up.|> android.animation.Animator.AnimatorListener
  com.github.mikephil.charting.jobs.AnimatedZoomJob -up-|> com.github.mikephil.charting.jobs.AnimatedViewPortJob
  com.github.mikephil.charting.jobs.AnimatedZoomJob o-- com.github.mikephil.charting.components.YAxis : yAxis
  com.github.mikephil.charting.jobs.MoveViewJob -up-|> com.github.mikephil.charting.jobs.ViewPortJob
  com.github.mikephil.charting.jobs.ViewPortJob .up.|> java.lang.Runnable
  com.github.mikephil.charting.jobs.ViewPortJob -up-|> com.github.mikephil.charting.utils.ObjectPool.Poolable
  com.github.mikephil.charting.jobs.ViewPortJob o-- com.github.mikephil.charting.utils.Transformer : mTrans
  com.github.mikephil.charting.jobs.ViewPortJob o-- com.github.mikephil.charting.utils.ViewPortHandler : mViewPortHandler
  com.github.mikephil.charting.jobs.ZoomJob -up-|> com.github.mikephil.charting.jobs.ViewPortJob
  com.github.mikephil.charting.jobs.ZoomJob o-- com.github.mikephil.charting.components.YAxis.AxisDependency : axisDependency


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
