@startuml

title __HIGHLIGHT's Class Diagram__\n

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.BarHighlighter {
        + BarHighlighter()
        + getHighlight()
        + getStackedHighlight()
        # getClosestStackIndex()
        # getData()
        # getDistance()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.ChartHighlighter {
        # mHighlightBuffer : List<Highlight>
        + ChartHighlighter()
        + getClosestHighlightByPixel()
        + getHighlight()
        # buildHighlights()
        # getData()
        # getDistance()
        # getHighlightForX()
        # getHighlightPos()
        # getHighlightsAtXValue()
        # getMinimumDistance()
        # getValsForTouch()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.CombinedHighlighter {
        + CombinedHighlighter()
        # getHighlightsAtXValue()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.Highlight {
        - mDataIndex : int
        - mDataSetIndex : int
        - mDrawX : float
        - mDrawY : float
        - mStackIndex : int
        - mX : float
        - mXPx : float
        - mY : float
        - mYPx : float
        + Highlight()
        + Highlight()
        + Highlight()
        + Highlight()
        + Highlight()
        + equalTo()
        + getAxis()
        + getDataIndex()
        + getDataSetIndex()
        + getDrawX()
        + getDrawY()
        + getStackIndex()
        + getX()
        + getXPx()
        + getY()
        + getYPx()
        + isStacked()
        + setDataIndex()
        + setDraw()
        + toString()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.HorizontalBarHighlighter {
        + HorizontalBarHighlighter()
        + getHighlight()
        # buildHighlights()
        # getDistance()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    interface com.github.mikephil.charting.highlight.IHighlighter {
        {abstract} + getHighlight()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.PieHighlighter {
        + PieHighlighter()
        # getClosestHighlight()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    abstract class com.github.mikephil.charting.highlight.PieRadarHighlighter {
        # mHighlightBuffer : List<Highlight>
        + PieRadarHighlighter()
        + getHighlight()
        {abstract} # getClosestHighlight()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.RadarHighlighter {
        + RadarHighlighter()
        # getClosestHighlight()
        # getHighlightsAtIndex()
    }
  }
  

  namespace com.github.mikephil.charting.highlight {
    class com.github.mikephil.charting.highlight.Range {
        + from : float
        + to : float
        + Range()
        + contains()
        + isLarger()
        + isSmaller()
    }
  }
  

  com.github.mikephil.charting.highlight.BarHighlighter -up-|> com.github.mikephil.charting.highlight.ChartHighlighter
  com.github.mikephil.charting.highlight.ChartHighlighter .up.|> com.github.mikephil.charting.highlight.IHighlighter
  com.github.mikephil.charting.highlight.ChartHighlighter o-- T : mChart
  com.github.mikephil.charting.highlight.CombinedHighlighter .up.|> com.github.mikephil.charting.highlight.IHighlighter
  com.github.mikephil.charting.highlight.CombinedHighlighter -up-|> com.github.mikephil.charting.highlight.ChartHighlighter
  com.github.mikephil.charting.highlight.CombinedHighlighter o-- com.github.mikephil.charting.highlight.BarHighlighter : barHighlighter
  com.github.mikephil.charting.highlight.Highlight o-- com.github.mikephil.charting.components.YAxis.AxisDependency : axis
  com.github.mikephil.charting.highlight.HorizontalBarHighlighter -up-|> com.github.mikephil.charting.highlight.BarHighlighter
  com.github.mikephil.charting.highlight.PieHighlighter -up-|> com.github.mikephil.charting.highlight.PieRadarHighlighter
  com.github.mikephil.charting.highlight.PieRadarHighlighter .up.|> com.github.mikephil.charting.highlight.IHighlighter
  com.github.mikephil.charting.highlight.PieRadarHighlighter o-- T : mChart
  com.github.mikephil.charting.highlight.RadarHighlighter -up-|> com.github.mikephil.charting.highlight.PieRadarHighlighter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
