@startuml

title __ANIMATION's Class Diagram__\n

  namespace com.github.mikephil.charting.animation {
    class com.github.mikephil.charting.animation.ChartAnimator {
        # mPhaseX : float
        # mPhaseY : float
        - mListener : AnimatorUpdateListener
        + ChartAnimator()
        + ChartAnimator()
        + animateX()
        + animateX()
        + animateXY()
        + animateXY()
        + animateXY()
        + animateY()
        + animateY()
        + getPhaseX()
        + getPhaseY()
        + setPhaseX()
        + setPhaseY()
        - xAnimator()
        - yAnimator()
    }
  }
  

  namespace com.github.mikephil.charting.animation {
    class com.github.mikephil.charting.animation.Easing {
        {static} + EaseInBack : EasingFunction
        {static} + EaseInBounce : EasingFunction
        {static} + EaseInCirc : EasingFunction
        {static} + EaseInCubic : EasingFunction
        {static} + EaseInElastic : EasingFunction
        {static} + EaseInExpo : EasingFunction
        {static} + EaseInOutBack : EasingFunction
        {static} + EaseInOutBounce : EasingFunction
        {static} + EaseInOutCirc : EasingFunction
        {static} + EaseInOutCubic : EasingFunction
        {static} + EaseInOutElastic : EasingFunction
        {static} + EaseInOutExpo : EasingFunction
        {static} + EaseInOutQuad : EasingFunction
        {static} + EaseInOutQuart : EasingFunction
        {static} + EaseInOutSine : EasingFunction
        {static} + EaseInQuad : EasingFunction
        {static} + EaseInQuart : EasingFunction
        {static} + EaseInSine : EasingFunction
        {static} + EaseOutBack : EasingFunction
        {static} + EaseOutBounce : EasingFunction
        {static} + EaseOutCirc : EasingFunction
        {static} + EaseOutCubic : EasingFunction
        {static} + EaseOutElastic : EasingFunction
        {static} + EaseOutExpo : EasingFunction
        {static} + EaseOutQuad : EasingFunction
        {static} + EaseOutQuart : EasingFunction
        {static} + EaseOutSine : EasingFunction
        {static} + Linear : EasingFunction
        {static} - DOUBLE_PI : float
    }
  }
  

  namespace com.github.mikephil.charting.animation {
    interface com.github.mikephil.charting.animation.Easing.EasingFunction {
        {abstract} + getInterpolation()
    }
  }
  

  com.github.mikephil.charting.animation.Easing +-down- com.github.mikephil.charting.animation.Easing.EasingFunction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
