@startuml

title __DATAPROVIDER's Class Diagram__\n

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.BarDataProvider {
        {abstract} + getBarData()
        {abstract} + isDrawBarShadowEnabled()
        {abstract} + isDrawValueAboveBarEnabled()
        {abstract} + isHighlightFullBarEnabled()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.BarLineScatterCandleBubbleDataProvider {
        {abstract} + getData()
        {abstract} + getHighestVisibleX()
        {abstract} + getLowestVisibleX()
        {abstract} + getTransformer()
        {abstract} + isInverted()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.BubbleDataProvider {
        {abstract} + getBubbleData()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.CandleDataProvider {
        {abstract} + getCandleData()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.ChartInterface {
        {abstract} + getCenterOfView()
        {abstract} + getCenterOffsets()
        {abstract} + getContentRect()
        {abstract} + getData()
        {abstract} + getDefaultValueFormatter()
        {abstract} + getHeight()
        {abstract} + getMaxHighlightDistance()
        {abstract} + getMaxVisibleCount()
        {abstract} + getWidth()
        {abstract} + getXChartMax()
        {abstract} + getXChartMin()
        {abstract} + getXRange()
        {abstract} + getYChartMax()
        {abstract} + getYChartMin()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.CombinedDataProvider {
        {abstract} + getCombinedData()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.LineDataProvider {
        {abstract} + getAxis()
        {abstract} + getLineData()
    }
  }
  

  namespace com.github.mikephil.charting.interfaces.dataprovider {
    interface com.github.mikephil.charting.interfaces.dataprovider.ScatterDataProvider {
        {abstract} + getScatterData()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
